using System;
using System.Collections;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Windows.Forms;
using System.Xml;
using System.Net.Mail;
using System.Net;
using System.Collections.Generic;
using System.Text;



namespace Dynamic.Script_8DA56D28018F327
{
	// Script generated by Pega Robot Studio 19.1.21.0
	// Please use caution when modifying class name, namespace or attributes
	[OpenSpan.TypeManagement.DynamicTypeAttribute()]
	[OpenSpan.Design.ComponentIdentityAttribute("Script-8DA56D28018F327")]
	public sealed class Script
	{
        public static string LinkedInDir = "C:\\Users\\shane.gracias\\LinkedinBot\\"; 

        public  void RenamePDF(string defaultFileName, string username)
        {
            username = RemoveBlankSpace(username); 
            string fileName = LinkedInDir + username + ".pdf";
            if (System.IO.File.Exists(defaultFileName))
            {
                System.IO.File.Move(defaultFileName, fileName);
            }
        }
        public string RemoveBlankSpace(string str)
        {
            str= str.Replace(" ", String.Empty);
            str = str.Replace("\n", String.Empty);
            return str;
        }

        public  void SuccessMail()
        {
            try
            {
                StringBuilder mailMessage = new StringBuilder();
                MailMessage mail = new MailMessage();
                mail.IsBodyHtml = true;
                SmtpClient smtp = new SmtpClient();
                smtp.Host = "smtp.gmail.com";
                smtp.Port = Convert.ToInt32("587");
                mail.From = new MailAddress("linkedshane@gmail.com");
                mail.To.Add("shanegracias7@gmail.com");
                mail.Subject = $"Test";
                mail.Body = "Test subject" +"<br/><br/><i>(This is an automated response. Do not reply.)</i>";
                smtp.EnableSsl = true;
                smtp.UseDefaultCredentials = false;
                smtp.Credentials = new NetworkCredential("linkedshane@gmail.com", "linkedINbot1");
                smtp.DeliveryMethod = SmtpDeliveryMethod.Network;
                smtp.Send(mail);
            }
            catch (Exception ex)
            {
                throw new Exception("Error while sending success email:" + ex.Message);
            }
        }

        public  List<string> GetAttachmentFileNames()
        {
            List<string> Filenames = new List<string>();
            string[] files = Directory.GetFiles(LinkedInDir);
            string Filename = string.Empty;
            foreach (string filePath in files)
            {
                //Filename = Path.GetFileName(filePath);
                Filenames.Add(filePath);
            }

            return Filenames;
        }
        public void Maintenance()
        {
            string[] files = Directory.GetFiles(LinkedInDir);
            foreach (string filePath in files)
            {
                System.IO.File.Delete(filePath);
            }
            System.IO.File.Copy("C:\\Users\\shane.gracias\\Desktop\\Connection_Record.xlsx", "C:\\Users\\shane.gracias\\LinkedinBot\\Connection_Record.xlsx");
        }




    }
}
